Fixed a bug which crashed the pan-detect. Thanks, @augelloantonio!
missed_peak = missed_section_peaks2[np.argmax(detection[missed_section_peaks2])]
TypeError: list indices must be integers or slices, not list
caused the Pan Tompkins peak detector to crash if peaks were
missing. That's been fixed as discussed here:
https://github.com/berndporr/py-ecg-detectors/issues/20